version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[deps] "
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[deps] "
  - package-ecosystem: "github-actions" # Check for GitHub Actions updates
    directory: "/" # The root directory where the Ansible role is located
    schedule:
      interval: "monthly" # Check for updates weekly
    commit-message:
      prefix: "[ci] "
